### ISSUE TITLE
Added this repo to the Raygun public documentation

### ISSUE THREAD

**Issue by sumitramanga** [springtimesoft/silverstripe-raygun-tags#1]
Hi there,

I wanted to reach out to thank you all for creating this awesome feature to support the SilverStripe Raygun module! 🤩

I've gone ahead and added this very useful feature to our public documentation which you can find here - https://raygun.com/documentation/language-guides/php/crash-reporting/silverstripe/#tags

If there is anything additionally to add or modify, do let me know andI'm happy to make changes!

Thank you once again! You may close this issue out :)

Kind regards,
Sumitra

**Comment by axllent** [comment]
Hi @sumitramanga. Thank you for reaching out and adding this repo to your public documentation :+1: I believe you have captured everything correctly as per our README, so no changes required from us.
